volumes:
  static_volume:

services:
  admin_panel:
    build:
      context: .
      dockerfile: docker_compose/admin.Dockerfile
    environment:
      DB_HOST: "pg_db"
    volumes:
      - static_volume:/opt/app/static
    ports:
      - "8000:8000"
    depends_on:
      - pg_db

  pg_db:
    image: postgres:16
    environment:
      POSTGRES_DB: "movies_database"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "123qwe"
    volumes:
      - $HOME/postgresql/data2:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./docker_compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker_compose/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_volume:/data/static
    depends_on:
      - admin_panel
    ports:
      - "80:80"